@startuml ClassDiagram
skinparam Style strictuml
' Remove strange Icons in Attributes
skinparam classAttributeIconSize 0

' Classes
Class EZWH

class User {
    + name
    + surname
    + email
    + password
}

class OrganizationalUnit
class OrganizationalUnitManager
class QualityOffice
class QualityOfficeManager
class WarehouseManager {
    + ID
}
class SupplierManager

Class Supplier {
    + name
    + address
    + P.IVA
}
Class Warehouse {
    + address
}
Class Company {
    + name
    + P.IVA
    + address
}

Class Order {
    + OrderID
    + transportation company name
    + tracking code
    + status
}

Class InternalOrder {
    + is_transported_by_a_company?
}

Class ExternalOrder

Class Item

note "The barcode is implemented by the Company, not the Supplier" AS N1

Class ItemDescriptor {
    + name
    + weight
    + dimensions
}
Class WarehouseCatalogue

class it_contains {
    + price
    + notes
}

Class MainCatalogue
Class SupplierCatalogue 
Class Test {
    + name
    + description
}

Class Shelf {
    + ShelfNumber
    + freeSpace
}

Class Sector {
    + SectorID
    + freeSpace
}

class manages {
    + quantity
}

class operated {
    + result
    + date
}

' Associations
User <-- OrganizationalUnitManager
User <-- QualityOfficeManager
User <-- WarehouseManager
User <-- SupplierManager

EZWH -- User
EZWH -- Warehouse

OrganizationalUnit <-- QualityOffice
OrganizationalUnit -- OrganizationalUnitManager : manages <
QualityOffice -- QualityOfficeManager : manages <
Company *-- "*" OrganizationalUnit
Warehouse -- Company: has a <
WarehouseManager -- Warehouse : manages >

Item -- ItemDescriptor

MainCatalogue -- EZWH
ItemDescriptor "*" -- "1" MainCatalogue: contained in >
 
ItemDescriptor "*" -- "*" SupplierCatalogue : contained in >
(ItemDescriptor, SupplierCatalogue) .. it_costs

Supplier -- SupplierCatalogue : has a 

WarehouseCatalogue -- ItemDescriptor : contained in <
Warehouse -- Item : stored in <

N1 .. Item

Sector  *-- "*" Shelf
Shelf "1" -- "*" Item: is in <

Order -- ItemDescriptor: has >
(Order, ItemDescriptor) .. manages

Order -- WarehouseManager : issues <
ExternalOrder -- Supplier : fills <

Order <-- InternalOrder
Order <-- ExternalOrder

OrganizationalUnitManager -- InternalOrder : issues >

Test -- Item : performed on >
Test -- QualityOfficeManager : perform <
(Test, Item) .. operated

@enduml