@startuml ContextDiagram
scale 2
left to right direction
skinparam packagestyle rect

' Actors
actor "Warehouse Manager" as WarehouseManager
actor "Supplier Manager" as SupplierManager
actor "Quality Office" as QualityOffice
actor "Transportation Service" as TransportationService
actor "Payment Service" as PayementService
actor "Cloud Service" as CloudService
actor "Organizational Unit Manager" as OrganizationalUnitManager
actor Administrator
actor "Warehouse Workers" as WarehouseWorkers
' Associations

rectangle System{
	WarehouseManager -- (EZWH)
	SupplierManager -- (EZWH)
	QualityOffice -- (EZWH)
	OrganizationalUnitManager --(EZWH)

	(EZWH) -- TransportationService
	(EZWH) -- PayementService
	(EZWH) -- CloudService
	
}

@enduml